CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
CALL FTL_INIT();
create table DimensionValue (
ID Int  primary key,
SORTORDER Int,
PARENTID Int,
CODE VARCHAR(100),
ABBREVIATION VARCHAR(20),
DESCRIPTION VARCHAR(100),
DIMENSIONID Int,
TREEDEPTH Int);
CALL FTL_CREATE_INDEX('PUBLIC', 'DIMENSIONVALUE', NULL);
