create table IF NOT EXISTS DimensionValue(
ID Int  primary key,
SORTORDER Int,
PARENTID Int,
CODE VARCHAR(100),
ABBREVIATION VARCHAR(20),
DESCRIPTION VARCHAR(100),
DIMENSIONID Int,
TREEDEPTH Int);
DELETE  FROM DimensionValue;