CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();
create table DimensionValue (
ID Int  primary key,
SORTORDER Int,
PARENTID Int,
CODE VARCHAR(100),
ABBREVIATION VARCHAR(20),
DESCRIPTION VARCHAR(100),
DIMENSIONID Int,
TREEDEPTH Int);
CALL FT_CREATE_INDEX('PUBLIC', 'DIMENSIONVALUE', 'CODE, DESCRIPTION, ABBREVIATION');
