Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (25,1,null,'100-120K',null,'100-120K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (26,2,null,'120-150K',null,'120-150K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (27,3,null,'150-200K',null,'150-200K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (23,4,null,'60-80K',null,'50-70K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (24,5,null,'80-100K',null,'80-100K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (28,6,null,'>200K',null,'>200K',1,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (3,1,null,'Computers',null,'Computers account',2,1);
Insert into DimensionValue (ID,SORTORDER,PARENTID,CODE,ABBREVIATION,DESCRIPTION,DIMENSIONID,TREEDEPTH) values (2,2,null,'Equipment',null,'Equipment',2,1);
